---

- name: Install repositories.
  apt_repository:
    repo="{{ item }}"
    update_cache=yes
  with_items: "{{ apt_install_repositories|default([]) }}"
  when: apt_install_repositories

- name: Remove repositories.
  apt_repository:
    repo="{{ item }}"
    state=absent
    update_cache=yes
  with_items: "{{ apt_remove_repositories|default([]) }}"
  when: apt_remove_repositories